name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Name of branch to base build on'
        type: string
        required: false
        default: 'main'
      build_branch:
        description: 'Name of branch to commit build to'
        type: string
        required: false
        default: 'build'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # リポジトリから全データをチェックアウト
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets['GITHUB_TOKEN'] }}
        ref: ${{ inputs.base_branch || 'main' }}
        fetch-depth: 0

    # Git configをGitHub ActionsのBotアカウントに設定
    - name: Set local git config user details
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    # 再度チェックアウトし、ビルド用ブランチにベースブランチをマージ(ビルド用ブランチが無いと失敗する可能性があるが続行)
    - name: (Re)checkout both branches and merge main into build
      continue-on-error: true
      run: |
        git checkout ${{ inputs.base_branch || 'main' }}
        git checkout ${{ inputs.build_branch || 'build' }}
        git merge ${{ inputs.base_branch || 'main' }}
    # Node.jsをセットアップ
    - name: Node.js setup
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    # pnpmをインストール
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
    # pnpmのstoreディレクトリ取得
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    # pnpmのキャッシュ系オプション設定
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # 依存パッケージをインストール
    - name: Install pnpm dependencies
      run: |
        pnpm i --frozen-lockfile

    # ビルドを実施
    - name: Build
      run: |
        pnpm run build
    # ビルドしたファイルをコミットする
    # 変更されたファイルがない場合失敗する場合があるが続行
    - name: Commit built files
      id: commit
      continue-on-error: true
      run: |
        git add -f dashboard extension graphics shared/dist
        git commit -m "Built files" -a
    # ビルド用ブランチにプッシュ
    - name: Push built files to build branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets['GITHUB_TOKEN'] }}
        branch: ${{ inputs.build_branch || 'build' }}
